In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
from src.pipelines.flow import run_pipeline
from pathlib import Path
import os
from hydra import initialize, compose
from omegaconf import OmegaConf
from hydra import compose
from hydra import initialize
from src.pipelines.flow import run_pipeline
from pathlib import Path
import os

In [7]:
with initialize(config_path=".", job_name=f"experiment_{Path.cwd().name}", version_base=None):
    cfg = compose(config_name="config.yaml")
    #print(OmegaConf.to_yaml(cfg))
    Xdict, scaler, meta = run_pipeline(cfg)

Removed existing directory: /home/dodeu/AGH/PD1/prototyping/data/raw
Unzipped /home/dodeu/AGH/PD1/prototyping/data/Dane - Polcom.zip → /home/dodeu/AGH/PD1/prototyping/data/raw
Unzip raw data stage complete.
Saved → /home/dodeu/AGH/PD1/prototyping/data/processed/Dane - Polcom/2022/M/VM01.parquet
Saved → /home/dodeu/AGH/PD1/prototyping/data/processed/Dane - Polcom/2022/M/VM02.parquet
Saved → /home/dodeu/AGH/PD1/prototyping/data/processed/Dane - Polcom/2022/M/VM03.parquet
Saved → /home/dodeu/AGH/PD1/prototyping/data/processed/Dane - Polcom/2022/M/VM04.parquet
Calculating RAM usage percent based on (ACTIVE/GRANTED) * 100 for R04
Saved → /home/dodeu/AGH/PD1/prototyping/data/processed/Dane - Polcom/2022/M/VM05.parquet
Calculating RAM usage percent based on (ACTIVE/GRANTED) * 100 for S
Saved → /home/dodeu/AGH/PD1/prototyping/data/processed/Dane - Polcom/2022/M/VM06.parquet
Saved → /home/dodeu/AGH/PD1/prototyping/data/processed/Dane - Polcom/2022/M/VM07.parquet
Calculating RAM usage percent based on (ACTIVE/GRANTED) * 100 for V03
Saved → /home/dodeu/AGH/PD1/prototyping/data/processed/Dane - Polcom/2022/M/VM08.parquet
Extraction stage complete.
{'VM06':                      CPU_USAGE_MHZ
DATE
2022-03-14 12:00:00        58567.0
2022-03-14 14:00:00        41881.0
2022-03-14 16:00:00        31048.0
2022-03-14 18:00:00        34468.0
2022-03-14 20:00:00        31933.0
...                            ...
2022-04-12 22:00:00        35485.0
2022-04-13 00:00:00        40423.0
2022-04-13 02:00:00        33106.0
2022-04-13 04:00:00        37600.0
2022-04-13 06:00:00        59916.0

[358 rows x 1 columns], 'VM03':                      CPU_USAGE_MHZ
DATE
2022-03-13 14:00:00        60035.0
2022-03-13 16:00:00        59883.0
2022-03-13 18:00:00        57655.0
2022-03-13 20:00:00        50277.0
2022-03-13 22:00:00        53088.0
...                            ...
2022-04-12 00:00:00        85847.0
2022-04-12 02:00:00        87466.0
2022-04-12 04:00:00       110286.0
2022-04-12 06:00:00       138615.0
2022-04-12 08:00:00       139214.0

[358 rows x 1 columns], 'VM07':                      CPU_USAGE_MHZ
DATE
2022-03-14 10:00:00        50549.0
2022-03-14 12:00:00        49843.0
2022-03-14 14:00:00        44727.0
2022-03-14 16:00:00        44258.0
2022-03-14 18:00:00        43164.0
...                            ...
2022-04-12 22:00:00        51329.0
2022-04-13 00:00:00        52929.0
2022-04-13 02:00:00        46803.0
2022-04-13 04:00:00        49478.0
2022-04-13 06:00:00        54998.0

[359 rows x 1 columns], 'VM08':                      CPU_USAGE_MHZ
DATE
2022-03-14 10:00:00        33489.0
2022-03-14 12:00:00        31045.0
2022-03-14 14:00:00        19552.0
2022-03-14 16:00:00        11383.0
2022-03-14 18:00:00        10239.0
...                            ...
2022-04-12 20:00:00         7769.0
2022-04-12 22:00:00         6073.0
2022-04-13 00:00:00         5723.0
2022-04-13 02:00:00         5719.0
2022-04-13 04:00:00        11796.0

[358 rows x 1 columns], 'VM04':                      CPU_USAGE_MHZ
DATE
2022-03-13 14:00:00        23328.0
2022-03-13 16:00:00        26699.0
2022-03-13 18:00:00        24804.0
2022-03-13 20:00:00        27643.0
2022-03-13 22:00:00        30995.0
...                            ...
2022-04-12 00:00:00        32788.0
2022-04-12 02:00:00        35067.0
2022-04-12 04:00:00        36286.0
2022-04-12 06:00:00        46117.0
2022-04-12 08:00:00        49206.0

[358 rows x 1 columns], 'VM01':                      CPU_USAGE_MHZ
DATE
2022-03-14 12:00:00            6.0
2022-03-14 14:00:00            7.0
2022-03-14 16:00:00            7.0
2022-03-14 18:00:00            7.0
2022-03-14 20:00:00            7.0
...                            ...
2022-04-13 00:00:00            7.0
2022-04-13 02:00:00            7.0
2022-04-13 04:00:00            7.0
2022-04-13 06:00:00            7.0
2022-04-13 08:00:00            7.0

[359 rows x 1 columns], 'VM02':                      CPU_USAGE_MHZ
DATE
2022-03-14 14:00:00         7087.0
2022-03-14 16:00:00         6055.0
2022-03-14 18:00:00         5975.0
2022-03-14 20:00:00         6097.0
2022-03-14 22:00:00         6206.0
...                            ...
2022-04-13 00:00:00         6176.0
2022-04-13 02:00:00         5806.0
2022-04-13 04:00:00         6118.0
2022-04-13 06:00:00         7436.0
2022-04-13 08:00:00         6830.0

[358 rows x 1 columns], 'VM05':                      CPU_USAGE_MHZ
DATE
2022-03-13 14:00:00        26896.0
2022-03-13 16:00:00        27084.0
2022-03-13 18:00:00        27501.0
2022-03-13 20:00:00        27819.0
2022-03-13 22:00:00        27444.0
...                            ...
2022-04-12 00:00:00        18363.0
2022-04-12 02:00:00        15254.0
2022-04-12 04:00:00        16281.0
2022-04-12 06:00:00        24963.0
2022-04-12 08:00:00        33239.0

[358 rows x 1 columns]}
Preprocessing stage complete.

In [17]:
for key in meta.keys():
    print(key)
    df = meta[key]
    print(df)

input_dim
1
output_dim
1

In [2]:
for key in Xdict.keys():
    print(key)
    df = Xdict[key]
    display(df)

VM06

,CPU_USAGE_MHZ,MEMORY_USAGE_KB,AVG_DISK_IO_RATE_KBPS,AVG_NETWORK_TR_KBPS
DATE,,,,
2022-03-14 12:00:00,0.866606,-0.761383,-0.274221,1.298418
2022-03-14 14:00:00,0.311066,-0.795418,0.332287,0.664044
2022-03-14 16:00:00,-0.049606,-0.811285,-0.454122,-0.433898
2022-03-14 18:00:00,0.064259,-0.824628,0.649441,0.168324
2022-03-14 20:00:00,-0.020141,-0.857486,0.177138,-0.244326
...,...,...,...,...
2022-04-12 22:00:00,0.098119,-0.869029,0.853423,-0.301921
2022-04-13 00:00:00,0.262523,-0.846373,2.920757,0.286621
2022-04-13 02:00:00,0.018913,-0.894305,0.350853,-0.272474
2022-04-13 04:00:00,0.168535,-0.882650,-0.053033,0.359898
2022-04-13 06:00:00,0.911519,-0.820338,-0.289130,0.138119

VM03

,CPU_USAGE_MHZ,MEMORY_USAGE_KB,AVG_DISK_IO_RATE_KBPS,AVG_NETWORK_TR_KBPS
DATE,,,,
2022-03-13 14:00:00,0.915481,1.807561,-0.167971,-0.692064
2022-03-13 16:00:00,0.910420,1.807783,-0.253811,-0.805913
2022-03-13 18:00:00,0.836242,1.807845,0.041840,-0.513917
2022-03-13 20:00:00,0.590600,1.807853,-0.147906,0.828581
2022-03-13 22:00:00,0.684189,1.807849,2.241105,2.185003
...,...,...,...,...
2022-04-12 00:00:00,1.774860,1.705289,0.079131,0.622671
2022-04-12 02:00:00,1.828763,1.704924,-0.200186,0.165730
2022-04-12 04:00:00,2.588527,1.705061,-0.255769,-0.367428
2022-04-12 06:00:00,3.531706,1.705244,0.016393,-0.367890
2022-04-12 08:00:00,3.551649,1.705251,0.422344,-0.629584

VM07

,CPU_USAGE_MHZ,MEMORY_USAGE_KB,AVG_DISK_IO_RATE_KBPS,AVG_NETWORK_TR_KBPS
DATE,,,,
2022-03-14 12:00:00,0.576151,1.011052,-0.121500,0.047653
2022-03-14 14:00:00,0.405820,1.011047,-0.121100,-0.052560
2022-03-14 16:00:00,0.390205,1.011044,2.411373,-0.075330
2022-03-14 18:00:00,0.353782,1.011054,1.683205,0.845810
2022-03-14 20:00:00,0.453397,1.011055,1.703496,2.848301
...,...,...,...,...
2022-04-12 22:00:00,0.625625,1.121204,0.416136,1.887422
2022-04-13 00:00:00,0.678895,1.121257,-0.087553,1.955356
2022-04-13 02:00:00,0.474938,1.121371,-0.131279,2.468659
2022-04-13 04:00:00,0.563999,1.121495,-0.176258,2.506378
2022-04-13 06:00:00,0.747780,1.121561,-0.133171,1.315766

VM08

,CPU_USAGE_MHZ,MEMORY_USAGE_KB,AVG_DISK_IO_RATE_KBPS,AVG_NETWORK_TR_KBPS
DATE,,,,
2022-03-14 10:00:00,0.031664,-0.858365,-0.228244,-0.447007
2022-03-14 12:00:00,-0.049706,-0.858867,-0.352800,-0.512099
2022-03-14 14:00:00,-0.432351,-0.878635,-0.354586,-0.546008
2022-03-14 16:00:00,-0.704328,-0.903339,-0.497661,-0.739263
2022-03-14 18:00:00,-0.742416,-0.909759,-0.505242,-0.752091
...,...,...,...,...
2022-04-12 20:00:00,-0.824652,-0.943677,-0.397179,-0.637636
2022-04-12 22:00:00,-0.881118,-0.935560,-0.488109,-0.747676
2022-04-13 00:00:00,-0.892771,-0.946017,-0.313498,-0.576108
2022-04-13 02:00:00,-0.892904,-0.947081,-0.519724,-0.796996
2022-04-13 04:00:00,-0.690578,-0.916763,-0.218691,-0.649410

VM04

,CPU_USAGE_MHZ,MEMORY_USAGE_KB,AVG_DISK_IO_RATE_KBPS,AVG_NETWORK_TR_KBPS
DATE,,,,
2022-03-13 14:00:00,-0.306634,0.278246,-0.614784,-0.668154
2022-03-13 16:00:00,-0.194400,0.278280,-0.540921,-0.630984
2022-03-13 18:00:00,-0.257492,0.278293,-0.567847,-0.656250
2022-03-13 20:00:00,-0.162971,0.278297,0.098396,-0.637347
2022-03-13 22:00:00,-0.051370,0.278415,0.174084,-0.516370
...,...,...,...,...
2022-04-12 00:00:00,0.008325,0.289032,0.995352,1.141875
2022-04-12 02:00:00,0.084202,0.289035,0.963937,1.691743
2022-04-12 04:00:00,0.124787,0.289034,0.335425,2.168221
2022-04-12 06:00:00,0.452098,0.289036,0.381403,2.222404
2022-04-12 08:00:00,0.554943,0.289054,0.284318,2.252273

VM01

,CPU_USAGE_MHZ,MEMORY_USAGE_KB,AVG_DISK_IO_RATE_KBPS,AVG_NETWORK_TR_KBPS
DATE,,,,
2022-03-14 12:00:00,-1.083111,-1.019096,-0.685102,-0.921653
2022-03-14 14:00:00,-1.083078,-1.019096,-0.685102,-0.921653
2022-03-14 16:00:00,-1.083078,-1.019096,-0.685022,-0.921653
2022-03-14 18:00:00,-1.083078,-1.019096,-0.685102,-0.921653
2022-03-14 20:00:00,-1.083078,-1.019096,-0.685062,-0.921350
...,...,...,...,...
2022-04-13 00:00:00,-1.083078,-1.019095,-0.685102,-0.921566
2022-04-13 02:00:00,-1.083078,-1.019095,-0.685182,-0.921653
2022-04-13 04:00:00,-1.083078,-1.019096,-0.685102,-0.921609
2022-04-13 06:00:00,-1.083078,-1.019096,-0.685142,-0.921609
2022-04-13 08:00:00,-1.083078,-1.019095,-0.684942,-0.921609

VM02

,CPU_USAGE_MHZ,MEMORY_USAGE_KB,AVG_DISK_IO_RATE_KBPS,AVG_NETWORK_TR_KBPS
DATE,,,,
2022-03-14 14:00:00,-0.847358,-0.253292,-0.485577,0.639640
2022-03-14 16:00:00,-0.881717,-0.253298,-0.328239,0.606135
2022-03-14 18:00:00,-0.884381,-0.253261,-0.392130,0.544621
2022-03-14 20:00:00,-0.880319,-0.253287,0.043272,0.952812
2022-03-14 22:00:00,-0.876690,-0.253237,-0.252139,0.383696
...,...,...,...,...
2022-04-13 00:00:00,-0.877689,-0.253259,-0.545651,0.301534
2022-04-13 02:00:00,-0.890007,-0.253264,-0.566414,0.224891
2022-04-13 04:00:00,-0.879620,-0.253262,-0.545850,0.441594
2022-04-13 06:00:00,-0.835739,-0.253264,-0.513176,0.634251
2022-04-13 08:00:00,-0.855915,-0.253270,-0.523088,0.655679

VM05

,CPU_USAGE_MHZ,MEMORY_USAGE_KB,AVG_DISK_IO_RATE_KBPS,AVG_NETWORK_TR_KBPS
DATE,,,,
2022-03-15 00:00:00,-0.186210,-0.950793,-0.155527,-0.478463
2022-03-15 02:00:00,-0.143528,NaN,-0.456493,-0.774067
2022-03-15 04:00:00,-0.042581,NaN,1.178810,-0.674590
2022-03-15 06:00:00,0.239284,NaN,0.529101,-0.622643
2022-03-15 08:00:00,0.332008,NaN,-0.219970,-0.530742
...,...,...,...,...
2022-04-10 16:00:00,-0.657017,NaN,-0.540295,-0.833474
2022-04-10 18:00:00,-0.643667,NaN,-0.542133,-0.836937
2022-04-10 20:00:00,-0.646863,NaN,-0.440972,-0.736579
2022-04-10 22:00:00,-0.635643,NaN,0.102579,0.008289
2022-04-11 00:00:00,-0.462082,-0.962268,1.559288,-0.085979